### ISSUE TITLE
Is the project starting SA-MP?

### ISSUE THREAD

**Issue by unkcs** [plakapenka/sasamp#2]
Is this project at least starting SA-MP? I compiled the project and tried to connect but there are errors in the Android Studio Log, is the project so unstable that it needs to be corrected to start SA-MP? I wanted to continue this project and try to finish it.

**Comment by plakapenka** [comment]
It's stable enough to run, but not for gaming.

Regarding your problem, I think that the problem is in the game files or not up-to-date links for api and the like

**Comment by unkcs** [comment]
The project was compiled, but when trying to enter the game, there are errors, such as public natives, an init example, among others;

**Comment by plakapenka** [comment]
I checked and it started fine) Give me the crash log, maybe I can help

**Comment by unkcs** [comment]
![image](https://github.com/plakapenka/sasamp/assets/69327493/50db8c57-83e5-4035-b7d3-a4bb5ce2518a)

When starting the project, there are these glitches in Android Studio and the game gets an infinite black screen.

I didn't change anything in the source code, I just compiled it.

**Comment by plakapenka** [comment]
did you change the name of the java packages? or toggle obfuscate

**Comment by plakapenka** [comment]
This is a strange error, I've never seen one like this)
He writes that he cannot find the init method, although it is in the game .so library and it is obviously there

**Comment by unkcs** [comment]
So, I never saw it either, that's why I started this topic, I just compiled the project, and started the game.

I'm using the BlueStacks 5 emulator, could this interfere with anything?

**Comment by plakapenka** [comment]
Don't know. I use my phone via USB

**Comment by unkcs** [comment]
Which game cache do you use? Could you share the link or upload it somewhere?

**Comment by plakapenka** [comment]
I can't do this. liverussia.online project cache

**Comment by plakapenka** [comment]
contact via telegram @plakapenka for faster answers
